### PR TITLE
Fixed Regular Expressions

### PR DESCRIPTION
**Pull request by AlexDorian7**
Fixed some regular expressions in the wildcard generator.
Made the strings into global regular expressions.

### CODE REVIEW

**Comment by rvion** [comment]
amazing, thanks !

@AlexDorian7 by the way, could you take a look at that https://github.com/rvion/CushyStudio/blob/master/docs/FAQ.md ? It's still a draft, and I should make that more proeminent in the readme :)

I'll merge in the meantime; feel free to ping me if you want to chat :)

**Comment by AlexDorian7** [comment]
@rvion How exactly do you want me to agree to the CLA

**Comment by rvion** [comment]
no place yet, I'll add a file right now.
By the way, is the FAQ good in your opinion ? I'd love any feeback / to hear your thoughts if you have any

**Comment by AlexDorian7** [comment]
Alright, I do have some suggestions for the file, overall I find the content to be good, but the format to be lacking. Also maybe consider splitting it into two FAQs. A user FAQ and a developer/contributor FAQ

**Comment by rvion** [comment]
okay, I setup some github bot 

cla-assistant
- https://github.com/cla-assistant/cla-assistant
- https://cla-assistant.io/

this should properly handle CLA changes, etc.

I pushed the CLA to some public gist here:

https://gist.github.com/rvion/3c263d5826c86db9ffe485374fe2d888

and I moved all the files in the repo to prepare the upcoming rephrasing you suggested :)

**Comment by rvion** [comment]
link to sign is here, I'll add it to the readme: https://cla-assistant.io/rvion/CushyStudio

but oh-gosh, this is so frightening to read; I really need to make it nicer 🙃

**Comment by rvion** [comment]
okay, maybe don't sign it now, I'm rewriting it so it's more in tune with what I want: free, open source, and soon GPLV3 once the everything is smooth and running :)

**Comment by rvion** [comment]
done @AlexDorian7 

you can sign the CLA in one-click here I think:

 https://cla-assistant.io/rvion/CushyStudio

**Comment by AlexDorian7** [comment]
Alright! I signed it!

**Pull request merged**
