### PR TITLE
Dock-Panel Header Overhaul

### PR DESCRIPTION
**Pull request by birdddev**
I noticed about halfway through this you already had a Panel_HeaderUI, so I can move this to there if these seem like good changes to you.
While attempting to keep the functionality of what's there already.
(I disagree with the option button being on every single header though, they should add that themselves if they need.)

This adds a \<HeaderUI\> and a \<SeparatorUI\> component, (Put in widgets because I'm not sure where I should be putting it)
You can see it being used in this PR in the Import Tab.

#### HeaderUI
- Automatically sets the height of children.
*Stuff in headers shouldn't have their height go past the bar, the draft headers are a special case and should draw their own stuff underneath this, if we use it there at all.*

#### SeparatorUI
- Should be used to push widgets to the right, or towards the center if used twice.
*This may look a little bad because it's not actually going to the center, but trying to fit, there should be a way to do this correctly.*
- This could also be used as a form.separator()?
*Would give app designers a simple way to control some layout stuff.*

#### Misc. Changes
- Cleaned up the Import tab a little.
- Made the Import tab use the new HeaderUI and SeparatorUI components.

### CODE REVIEW

**Comment by birdddev** [comment]
I was going to move in to/replace Panel_HeaderUI with this if you gave me the go ahead, and then move everything that wasn't using it to use it before marking it ready.

**Comment by rvion** [comment]
oh x)
should have read that better !
I had no strong opinion, cause the header I added was done in a hurry without much heavy thinging. just wanted a place to add stuff, possibly with the tooltip system, to make sure it wouldn't take too much space on small screen.

Honestly, those changes feel pretty safe (no hidden stuff hard to see), I kinda totally trust you on this one. Usually, when you touch something in the UI, it's way better after, so, all green for me ! ❇️

**Comment by birdddev** [comment]
Okay, I'll work on moving everything to it in a bit, every header for dock-panels should be very consistent afterwards, except the app draft one which needs its own special stuff at the top.

**Comment by birdddev** [comment]
Let me know if you have any gripes with the FavBar changes.

**Comment by birdddev** [comment]
Everything should be updated now.

**Pull request merged**
